version: "3.9"

services:
  mak3it:
    build: .
    image: fullpadge/mak3it:latest
    container_name: mak3it-app
    environment:
      - NODE_ENV=production
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - COMPANY_NAME=Mak3it
      - COMPANY_EMAIL=contact@mak3it.com
      - COMPANY_WEBSITE=https://mak3it.org
    ports:
      - "5005:5005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/mak3it/workspace:/workspace
      - /root/mak3it/data:/app/data
    restart: always
    command: make run
    depends_on:
      - sandbox

  sandbox:
    image: hexdolemonai/lemon-runtime-sandbox:latest
    container_name: mak3it-sandbox
    privileged: true
    restart: always
    volumes:
      - /root/mak3it/workspace:/workspace
