version: "3.9"

services:
  mak3it:
    build: .                          # <-- on build depuis TON Dockerfile
    image: fullpadge/mak3it:latest    # <-- nomme ton image
    container_name: mak3it-app
    environment:
      - NODE_ENV=production
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - COMPANY_NAME=Mak3it
      - COMPANY_EMAIL=contact@mak3it.com
      - COMPANY_WEBSITE=https://mak3it.org
    ports:
      - "5005:5005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/mak3it/workspace:/workspace
      - /root/mak3it/data:/app/data
    restart: always                   # <-- pour relancer auto si crash
    stdin_open: true
    tty: true
    command: make run
