version: "3.9"

services:
  mak3it:
    build: .
    image: fullpadge/mak3it:latest
    container_name: mak3it-app
    environment:
      - NODE_ENV=production
      - COMPANY_NAME=Mak3it
      - COMPANY_EMAIL=contact@mak3it.com
      - COMPANY_WEBSITE=https://mak3it.org
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - DOCKER_HOST_ADDR=host.docker.internal
      - ACTUAL_HOST_WORKSPACE_PATH=${WORKSPACE_BASE:-/workspace}
      - SANDBOX_URL=http://sandbox:5005
    ports:
      - "5005:5005"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.cache:/.cache
      - ./workspace:/workspace
      - ./data:/app/data
    command: make run
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - sandbox
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sandbox:
    image: hexdolemonai/lemon-runtime-sandbox:latest
    container_name: mak3it-sandbox
    privileged: true
    restart: always
    tty: true
    stdin_open: true
    volumes:
      - ./workspace:/workspace
      - ./data:/app/data
      - ~/.cache:/.cache
